export const enum FundingStatus {
  PENDING = "PENDING",
  INCOMPLETE = "INCOMPLETE",
  UNCONFIRMED = "UNCONFIRMED",
  ONE_CONFIRMATION = "ONE_CONFIRMATION",
  CONFIRMED = "CONFIRMED",
  COMPLETED = "COMPLETED",
}
